spring:
  data:
    mongodb:
      username: ateaf
      password: ateaf
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: prg.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ateaf.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.ateaf.ecommerce.kafka.payment.PaymentConfirmation

  mail:
    host: localhost
    port: 1025
    username: ateaf
    password: ateaf
    properties:
      smtp:
        trust: "*"
      auth : true
      starttls:
        enabled: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000

server:
  port: 8040