server:
  port: 8070
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        show_sql: true;
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: prg.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.ateaf.ecommerce.kafka.OrderConfirmation

application:
  config:
    customer-url: http:\\localhost:8222/api/v1/customers
    product-url: http:\\localhost:8222/api/v1/products
    payment-url: http:\\localhost:8222/api/v1/payments
